### ISSUE TITLE
能否对视频文件名预处理一下？

### ISSUE THREAD

**Issue by gtjl12** [evgo2017/bilibili_video_download#10]
作者大大您好，
我在下载这个视频时，https://www.bilibili.com/video/av65285622 ，
aria2提示“ Failed to open the file ”，可能是文件名是“American Factory | Netflix.FLV ”，而“|”是windows系统不允许的文件名字符。
不知道在下载前，替换掉文件名里不合法的字符是否可行？

**Comment by evgo2017** [comment]
@gtjl12  已完善。之前只对视频【文件夹】名称进行了格式化，现已补充对视频【文件】名称的格式化。在 windows 系统下已成功下载。

谢谢交流。
相关更改：[commits](https://github.com/evgo2017/bilibili_video_download/commit/82776b898b683ecf9d9f9b3eab1a476e31c7f959)

**Comment by gtjl12** [comment]
感谢您的修改！
已测试过，没有问题！
