### ISSUE TITLE
远程RPC请求出错:[object ProgressEvent]

### ISSUE THREAD

**Issue by lirener** [evgo2017/bilibili_video_download#11]
远程RPC请求出错:[object ProgressEvent]
确定hosts存在127.0.0.1 localhost
设置把localhost改成127.0.0.1问题解决……
使用aria2c 版本号V:1.34 线程破解版
脚本版本号：最新1.2.3.190905 版本?
<a href="https://imgbb.com/"><img src="https://i.ibb.co/ynmwGjM/QQ-20190929050641.jpg" alt="QQ-20190929050641" border="0" /></a>
特别需求：港澳台番剧解析支持……
主要还是为了这个 因为看港澳台特别卡……已经用了解除限制脚本的说

**Comment by lirener** [comment]
还有个功能请求 强迫症看到旁边多了东西 很不适应……希望作者能把整个UI界面
加个 显示/隐藏 的按钮开关 呼出和隐藏 界面 这样比较美观……
具体为什么 我还是再来个图……因为我开了夜间模式....特别明显这个脚本 
<a href="https://ibb.co/Tvn6xDT"><img src="https://i.ibb.co/vwrp6CB/QQ-20190929054110.jpg" alt="QQ-20190929054110" border="0" /></a>
还有脚本似乎不支持部分番剧加载 比如地下城……https://www.bilibili.com/bangumi/play/ep276647
原因未知……等作者自行排查一下……找不到叫我 ……我来排查

**Comment by lirener** [comment]
还有关于 设置自定义路径问题……【E:\aria2\aria2-Downloads\】是对的 
必须\结尾 不然附加文件夹会进不去……
不管我怎么设置 他都没办法以 ./结尾 因为脚本会把名字加在最后面
还有我是windows系统……不是linux……这个斜杠好像反了？
【./aria2-Downloads/】这样虽然能下 但是他不会下到文件夹里面去 是安装目录下载
总之我解决了……

**Comment by evgo2017** [comment]
@lirener ① localhost 一般默认指向 127.0.0.1，用不了就自己指定 IP。② 港澳台相关没有接触，显示隐藏可通过关闭打开脚本解决，近期没有时间开发新功能，见谅。③ 提供的番剧可正常下载。④ 基础路径后面有个括号，里面写了必须以'/'结尾。 ⑤ windows 下 './' 正常下载，没有问题。可使用 'C:/data/' 下载，与是否为 Linux 无关。'./' 为当前目录，所以会在安装目录。

**Comment by lirener** [comment]
localhost是默认配置……但是我在百度云网页版解析也用localhost就没出现这个问题
用这个脚本默认配置的localhost会出现添加失败 所以才觉得是脚本问题...
所以才报告~望排查..默认无cookies清除缓存后都会重制为默认……
港澳台是有B站限制解除的脚本 视频加载正常播放了 【bilibili_video_download】也不会加载……
另外显示虽然可以通过开关脚本解决 但是不是立马 要刷新网页……
<a href="https://imgbb.com/"><img src="https://i.ibb.co/HT782c3/image.jpg" alt="image" border="0" /></a>

**Comment by evgo2017** [comment]
@lirener localhost 是网络问题，请自行解决。数据保存在 localStorage，清除缓存肯定没了，不要缓存就直接把插件代码的默认值改为你自己需要的。是否是两个插件之间有冲突呢？目前没有时间添加新功能，有 BUG 我会解决，但不解决兼容问题。我很认真的看问题了，谢谢。

**Comment by evgo2017** [comment]
@lirener 哎，显示隐藏插件已经加了（[commit](https://github.com/evgo2017/bilibili_video_download/commit/e7941c599cb4751a9683f854605fa1f1baa514e3)），更新脚本就有了。

此外更新文档里面这个 issues 就不链接了，相关度不高。说一些个人看法，你可以参考其他人的 issues 怎么提，一个问题一个 issues，简洁明了，这不是聊天。与这个标题无关的我删除了。

**Comment by lirener** [comment]
localhost 应该不是网络问题那么简单…… 因为我抓包都看不到 localhost的
我说的这些问题 都是可以稳定复现的……100% 存在 no exception
<a href="https://wx4.sinaimg.cn/large/0066ebxvgy1g7kj79bp0gg312v0moqv9.gif"><img src="https://wx4.sinaimg.cn/large/0066ebxvgy1g7kj79bp0gg312v0moqv9.gif" alt="image" border="0" /></a>

**Comment by lirener** [comment]
原因似乎已经找到了 我本机会先走IPV6再走IPV4大约失败2次后才走的IPV4
![QQ截图20191003065238](https://user-images.githubusercontent.com/19354130/66087683-fc345580-e5aa-11e9-908e-7567b9acb088.png)

**Comment by evgo2017** [comment]
@lirener 那这个 issues 我就关了？

**Comment by lirener** [comment]
...问题没有解决 不知如何解决 我尝试关闭网卡的IPV6协议 仍然不行……

**Comment by evgo2017** [comment]
@lirener  这是你电脑的问题，不是插件问题，谢谢。

**Comment by evgo2017** [comment]
@lirener  这个插件我是有什么责任和义务来负责吗？我是必须要保证每个人都可以使用吗？您把我的情分践踏的一无是处。您觉得我的插件有问题，请您别用可以吗。一直拿我的跟其他人的比，您用他们的好吗？您没有必要在我的插件上浪费时间了，谢谢您。

**Comment by lirener** [comment]
我觉得现在这样的你不适合再继续下去~当你发起项目的时候 当然就有义务和责任对自己的项目负责
当别人问题还没解决的时候 你就急着关闭~觉得别人的问题不耐烦~巴不得立刻马上~
问题是虽然很小~但是从你的态度可以看出来 既然不喜欢了 何必继续下去
你解决不来的问题 可以大家帮忙解决 没必要把东西都往自己身上揽
github的目的~不就是因为这样而存在吗？
说话不能太肯定 特别出了问题的时候..因为你的推断有可能是错误的.
比较的这个话题 太复杂 要谈论起来怕是1天都不会结束 我只简单的说 行不行 能不能 就是..
如果真的想做好一个东西 我怕 比较是必不可少的..
抓住问题 解决问题 这个才是关键的！~

**Comment by evgo2017** [comment]
@lirener 你先分清楚，这是我的自用。你也不要长篇大论了。到此为止。

**Comment by lirener** [comment]
如果你现在想清楚了要自己用的话 那把这个通道也给关了吧~ 我想应该没人会再来烦你
<img src="https://s2.ax1x.com/2019/10/07/u2i5k9.jpg" alt="u2i5k9.jpg" border="0" />
不是别人没搞清楚 如果你先搞清楚 分享的意义 ~ 就不要说些不负责任的话
