### ISSUE TITLE
个别视频脚本加载失败[Loading Failed]

### ISSUE THREAD

**Issue by lirener** [evgo2017/bilibili_video_download#12]
连接地址：https://www.bilibili.com/bangumi/play/ep276647
<a href="https://imgchr.com/i/uGbWpq"><img src="https://s2.ax1x.com/2019/09/30/uGbWpq.jpg" alt="uGbWpq.jpg" border="0" /></a>

**Comment by evgo2017** [comment]
这个没问题。你测试的时候先保证环境干净，其他插件关了再试吧。

**Comment by lirener** [comment]
先附上 新脚本的测试报告：隐藏是可以没问题了……
就是点【>】显示的时候 会有个明显的延迟 大约3秒左右……希望能降到1秒...
-------------------------------
另外这个视频确实不加载脚本 已经测试了关闭其他脚本 和关闭其他插件的环境运行
其他视频基本都是正常的 就个别几个 比如地下城的这个
* [ep276647](https://www.bilibili.com/bangumi/play/ep276647) 不正常
我可以稳定复现这个问题  还支持远程排查……
<a href="https://ibb.co/F07rdt2"><img src="https://i.ibb.co/cCTBsd0/11111111111111.png" alt="11111111111111" border="0" /></a>
不知道是不是和我的谷歌游览器版本有关系 比较旧 而且也不能更新...
(更新了的话youku html5 player+ 就不支持 我感觉不是谷歌的问题)

**Comment by lirener** [comment]
Telegram：@lirener
QQ：17070453
远程用……作者收到可以帮我删除

**Comment by evgo2017** [comment]
@lirener 延迟原因还是因为网络，请求数量与网速。要获取每部分的详细信息，需要分别发请求，暂时不可避免。以你举例的剧集，12+请求是 1.67s；其他 50+请求 4.6s，单个视频不到 1s。[请求相关图片](https://ibb.co/2jF7XDf)

此外 [ep276647](https://ibb.co/Xx0Jq1y) 完全正常，与插件无关，我建议你看看网络，这个视频单纯加载速度都很慢。

**Comment by lirener** [comment]
就是加载不了脚本 不骗你 就这个视频 稳定不能加载的 别的都可以的
网络没问题 视频都能播放

**Comment by evgo2017** [comment]
@lirener  是的，这个是插件问题，但是我无法解决，不好意思。

**Comment by lirener** [comment]
你这样根本就不是解决问题 而是在逃避问题
我说了不是插件问题 如果是 那你应该告诉我是哪个插件问题？我关掉测试
你把整个都关了 能解决的人以后也看不到了..最错误的决定
没必要再回复了我 我发现了更多的BUG...

**Comment by evgo2017** [comment]
@lirener  是的，都是我插件的问题，请你不要再使用了，不要再花费你宝贵的时间来做测试了，我的插件不值得，你去用其他人的插件吧，谢谢。就此为止。

**Comment by lirener** [comment]
这个不是【bilibili_video_download】脚本的问题 
是扩展【 uBlock Origin】的问题 
而且很邪门 之前测试的时候 已经关掉了刷新都不行 后来第二天我直接换成别的启用就可以了
