### ISSUE TITLE
我这里出问题了

### ISSUE THREAD

**Issue by 1468507695** [evgo2017/bilibili_video_download#14]
本来是可以下载视频的，可是我在收藏点了一下“量大卡顿，等待即可”之后，在视频的播放页左边就没有插件显示了
https://www.bilibili.com/video/av     没有显示插件按钮
https://space.bilibili.com/      www.bilibili.com/bangumi/play/ep    有按钮显示
卸载重装插件也不行，换浏览器也不行，请问怎么解决？

**Comment by 1468507695** [comment]
额，它自己又好了。。。我什么都没做它就自己显示出来了，真是玄学

**Comment by evgo2017** [comment]
@1468507695 数据量很大加载时间会比较长。
