### ISSUE TITLE
请问支持推送到远端服务器下载吗？

### ISSUE THREAD

**Issue by JIA-Jimmy** [evgo2017/bilibili_video_download#15]
想推送到挂载谷歌云盘的vps上下载b站的教程视频，但是填了远程服务器的aria地址和RPC后在PC下载没有用

**Comment by evgo2017** [comment]
@JIA-Jimmy 支持的，我平时用 NAS 接收。你在控制台看看是否发了请求，如果还有问题可以给我发邮件或 vx 附图。
