### ISSUE TITLE
希望aria2的rpc设置能做成配置保存，而不是像现在这样硬编码在代码里面

### ISSUE THREAD

**Issue by mkanako** [evgo2017/bilibili_video_download#2]
因为如果你的脚本更新了，我的配置不就被覆盖了

**Comment by evgo2017** [comment]
新增了设置页，采用 Cookie 的方式保存，非常感谢你的建议~
[相关提交](https://github.com/evgo2017/bilibili_video_download/commit/c8b0e1ce2524e481fc88839caa3d2753a497098f)

**Comment by mkanako** [comment]
@mkanako 
嗯，虽然cookie也行，但是存在不少缺点

**Comment by mkanako** [comment]
> 本可用 GM_setValue && GM_getValue 存储，但是由于代码需要页面的上下文来获取一些数据，所以必须设置 grant 为 none，故不可用 GM_* 等功能

额，抱歉，没看到readme更新了说明，一时还是没理解为什么不能用GM_\*。。。。
但话说回来，就算不能用GM_\*，那存在localStorage总行吧，也比随时可能被清除的cookie好点

**Comment by evgo2017** [comment]
@mkanako 
因为 GM_* 需要设置 grant，会在沙盒中运行，而目前部分数据是从页面上下文（window 对象，grant: none）直接获得的（减少请求），所以没有采用 GM_* 的方式。回复中忘记写原因了不好意思。
之后我再权衡一下。谢谢~

**Comment by mkanako** [comment]
@evgo2017 哦，大概有点理解了，我油猴脚本写得少，还不知道这种情况，哈哈~~

**Comment by evgo2017** [comment]
@mkanako  

> If @ grant is followed by 'none' the sandbox is disabled and the script will run directly at the page context. In this mode no GM_* function but the GM_info property will be available.

我最开始是设置了 GM_*，但发现一直读取不到数据，还以为是定时器出错了，之后发现 window 对象不对劲，再看了看[文档](https://www.tampermonkey.net/documentation.php?ext=dhdg#_grant)的时候发现的。
已用 Local Storage 替代了 Cookies。数据存储方面的实践再进一步~
