### ISSUE TITLE
aria2的rpc目录设置有bug

### ISSUE THREAD

**Issue by mkanako** [evgo2017/bilibili_video_download#3]
https://github.com/evgo2017/bilibili_video_download/blob/c652209fe55777c8e7fb3afa3ce4dc5a239d9968/index.js#L420

这里应该是
{ 'referer': `${REFERER}`, 'out': `${out}.FLV`, 'dir': `${BASEDIR}${dir}` }

**Comment by evgo2017** [comment]
[已修复](https://github.com/evgo2017/bilibili_video_download/commit/c8b0e1ce2524e481fc88839caa3d2753a497098f#diff-168726dbe96b3ce427e7fedce31bb0bcR463)，感谢！
