### ISSUE TITLE
小白怎么使用？

### ISSUE THREAD

**Issue by Co-xuan** [evgo2017/bilibili_video_download#8]
用没有详细教程？aira是啥？怎么使用？Yaaw呢？怎末配置？哪里配置？

**Comment by evgo2017** [comment]
文档已经非常详细了。Aira2 相关知识请查询。初步使用不需要配置，下载软件运行即可。

**Comment by lirener** [comment]
aira……都没配置好的话 建议是百度学一下 或者放弃……难是不难 别人都写了一键运行脚本的 
或者你知道朋友的IP和端口的话 可以在脚本设置 填写IP+端口 和 web端ari2c的下！
但是这样比较繁琐 下载的视频是在别人服务器上 你还要再缓存回来
……我刚刚好在B站别人脚本那边看到个视频教程 发出来好像不大合适吧？
还是发吧：https://www.bilibili.com/video/av61865580
